# Generated by Django 5.0.1 on 2024-02-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
