# Generated by Django 5.0.1 on 2024-02-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualshift',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shifts',
            name='type',
        ),
        migrations.AddField(
            model_name='shifts',
            name='end',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifts',
            name='start',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shifts',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
