# Generated by Django 5.0.1 on 2024-02-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_shifts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualshift',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='date',
            field=models.DateField(),
        ),
    ]
