# Generated by Django 5.0.1 on 2024-02-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_actualshift_date_alter_shifts_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actualshift',
            old_name='users',
            new_name='user',
        ),
    ]
